### ISSUE TITLE
Only updating inventory

### ISSUE THREAD

**Issue by Softiing** [d-haxton/HaxtonBot#100]
The bot is just updating inventory all the time, doing nothing else. why? :(

**Comment by ElectroZoom** [comment]
Same here...

**Comment by Max604** [comment]
You've most likely been soft banned.

**Comment by Softiing** [comment]
@Max604 how long does it last?

**Comment by TemhAAhmeT** [comment]
Always answer is softban to everything around here. Ok soft ban but almost all bots can unban in 10 sec.
but problems in haxton remains always.

**Comment by Littlem0nk3y** [comment]
@Softiing For me, the softban takes around 5 mins. This happened because you had open too many bots at a time, if you dont want it to happen try with 1-2 bots/computer.
