### ISSUE TITLE
Some good farming coords

### ISSUE THREAD

**Issue by sandor111** [d-haxton/HaxtonBot#102]
please use different coords
{
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      },
      {
        "Latitude": 43.64017,
        "Longitude": -79.375748
      },
      {
        "Latitude": 40.764871,
        "Longitude": -73.9734972
      },
      {
        "Latitude": 37.779669924659004,
        "Longitude": -122.41138458251953
      },
      {
        "Latitude": 34.012257773782864,
        "Longitude": -118.49441528320311
      },
      {
        "Latitude": 22.285661566028704,
        "Longitude": 114.15020227432251
      },
      {
        "Latitude": 22.285661566028704,
        "Longitude": 114.150202274322
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      }

**Comment by chen701** [comment]
just copy it into the  config file ？ or need something else ？

**Comment by sandor111** [comment]
Yes
