### ISSUE TITLE
"Updating inventory" (BUG?) continues in v1.1

### ISSUE THREAD

**Issue by Gernatch** [d-haxton/HaxtonBot#108]
Is this a bug? Since it persists in the new version, I'm wondering if this is something I am doing wrong. It's entirely intermittent. Not sure what the trigger is. I just let my computer sit around for a while, and eventually it starts working again. Running Windows 10 in a VirtualBox Environment.

**Comment by Gernatch** [comment]
Changed my coordinates (slightly) and reopened and it worked. Not sure if this has anything to do with it. Could be coincidence.

**Comment by MiGaBelG** [comment]
im gonna try that now xD
