### ISSUE TITLE
Issue solved ! "UPDATING INVENTORY"

### ISSUE THREAD

**Issue by MiGaBelG** [d-haxton/HaxtonBot#117]
i've managed to fix the problem.
All i did was restarting the bot run quickspinner 5x and changed coördinates of the bot !
I hope it helps y'all

**Comment by pzmkr** [comment]
where to find quickspinner?

**Comment by MiGaBelG** [comment]
just google it ;)

**Comment by EcoBike** [comment]
doesn't work for me sadly :/

**Comment by MiGaBelG** [comment]
Try to redo the steps :) and take other coordinates

**Comment by Boomstamtak** [comment]
Same problem here, even with the latest version. I think i teleported to some random location and can't seem to get out.

**Comment by vehrbox** [comment]
i restart my wifi router an it works for me.

**Comment by Kern3lErr0r** [comment]
People...It's not a bug, it simply runs out of pokemon to catch in that area *facepalm*...It keeps updating inventory periodically, but there's nothing nearby that's new to catch for a while that's in range.

**Comment by Gernatch** [comment]
@Kern3lErr0r , we are getting stuck on semantics. It's doing this indefinitely, requiring some kind of intervention. Lets call it an "issue"...

**Comment by Gernatch** [comment]
The fix again and again seems to be time... Is it overheating? XD

**Comment by Kern3lErr0r** [comment]
It goes into a "resting" state after it clears the area with burst catches, waiting for new spawns until it's next burst. It's not an issue, it's simply how it works.

**Comment by Gernatch** [comment]
Okay. Is it supposed to take 7+ hours (overnight) for stuff to spawn? Again, this is indefinite.

**Comment by Suzano-Sho** [comment]
@Kern3lErr0r I have to say, it hardly seems like a "resting state" when it factually does do nothing but update inventory for 8+ hours overnight...I've never been anywhere where Pokemon take that long to spawn and I can confirm that using the normal Pokemon Go app in the exact same location, pokemon immediately spawned for me...yet the bot did nothing but update inventory...

**Comment by Gernatch** [comment]
Yeah, it's not resting, it's going to sleep for the night. And that's my job. 

It almost seems like a ban of some kind because the only fix it to log off for a while. That's the only thing that has consistently fixed it for me. I tried opening it every 10 minutes today, and it didn't work. I waited an hour before reopening, and it worked again. That's the fix every time.

**Comment by vehrbox** [comment]
I ran it for about an hour or so during the update inventory phase but nothing happen. So I tried reseting the router and it goes back to normal. It's currently running for about 2 hours now and I'm just gonna leave it there. So we'll see what gonna happen in a couple of hours.

**Comment by VasTShadowZ** [comment]
If you run more than 1 bot on the same IP Address.. It will flag your IP. The bot "Updates Inventory" When it cant find any PokeStops. When you are IP Flagged. No PokeStops will show up.. Therefore In a Loop of "Updating Inventory"... To fix this. Download a VPN and Switch IP Addresses.

**Comment by Gernatch** [comment]
Based on the definition of the latest release, it looks like this may be patched to not happen. Will be testing once unflagged.

**Comment by Gernatch** [comment]
2 hours and 10 minutes and going strong since last update.

**Comment by UraharaKisuke07** [comment]
Can confirm. Ver 1.2 doesn't have the inventory error.

**Comment by TurntKFC** [comment]
Vpn helps to u guys getting temporary ip ban i recommend cyberghost and make sure u arent running any other bots like necrobot, pokebuddy, pokesniper, etc it will get u ip ban fix just reset ur router wait 5-10 min then try again

**Comment by loveintrt** [comment]
Any good free VPN recommended? better with private ip and coming with password/username.

**Comment by poopiscool** [comment]
UraharaKisuke07, please can u link the new version of haton on this forum please, i cant seem to find it

**Comment by UraharaKisuke07** [comment]
@loveintrt  Cyberghost is really great VPN and free. 
@poopiscool  https://github.com/d-haxton/HaxtonBot/releases. get the one with "IP ban avoidance".

**Comment by poopiscool** [comment]
i downloaded the cybergost vpn but what setting do i turn on to not get ban

**Comment by UraharaKisuke07** [comment]
@poopiscool Install Cyberghost. Click on "Protect my internet connection" and once it connects to a new IP you'll good to go. 
To anyone wondering if the new version works, see this http://imgur.com/a/8Lemf . A Proof (look the the time running and the exp is without lucky eggs and evolving.

**Comment by poopiscool** [comment]
Honestly thank you alot, i thought i got ip ban for ever cuz it kept saying updating inventory. It is working perfectly now

**Comment by poopiscool** [comment]
1 hour in, the bot started to display Error in catching pokemon, (Catch Error), so i closed haxton and started it again, now its back to the updating inventory error, please help

**Comment by poopiscool** [comment]
Encounter not in range
please help

**Comment by poopiscool** [comment]
yo, how do you get around having too many pokemon in inventory, cuz after an hour or two, it just starts saying inventory full, and so i have to go into app and transfer pokemon manually
