### ISSUE TITLE
I stand at a place with alot of pokemons, start the bot and nothing happens..

### ISSUE THREAD

**Issue by Softiing** [d-haxton/HaxtonBot#119]
as the title says,  what is the problem?? I've tried to re-download the client but nothing works

**Comment by UraharaKisuke07** [comment]
what error are you getting?

**Comment by Softiing** [comment]
just saying updating inventory @UraharaKisuke07

**Comment by teejvyx** [comment]
Means you've been soft banned, need to change you're ip or wait 1-2 hours @softiing
