### ISSUE TITLE
encounter failed with reason : encounter not in range

### ISSUE THREAD

**Issue by maximoney1994** [d-haxton/HaxtonBot#120]
bot runs fine for about 20 minutes then continues on spamming.
" encounter failed with reason : encounter not in range"
and updating inventory.

![68639a5afc494b199e17badeeb07374d](https://cloud.githubusercontent.com/assets/17068496/17570863/5df15926-5f4e-11e6-851f-607ae62f2973.png)

**Comment by arthurrxd** [comment]
yeah this happens to me too and i get alot of updating inventory

**Comment by Utopik** [comment]
i have like this error, too

**Comment by crownknuckles** [comment]
Me too, how do I fix it?

**Comment by UraharaKisuke07** [comment]
Softban most likely. Open app on your phone, can you see pokestops? Can you loot them? Report back.

**Comment by josh808** [comment]
I tested about 5 times. Each time I get IP banned for about an hour. It will run fine for about 15 mins before giving the errors. No other bots running other than this. When I check my phone no pokestops or Pokemon, switch the wifi off and turn on cellular data and everything is back to normal.
