### ISSUE TITLE
When you want to donate, but the thing just doesn't work :/

### ISSUE THREAD

**Issue by cerravox** [d-haxton/HaxtonBot#123]
Hoping it would work, but Updating inventory..... and I have changed my IP and nothing.... I have also changed coordinates.... and nothing.... Yes, I have also restarted my router.....and I guess its time to take my business else where...

**Comment by UraharaKisuke07** [comment]
Wait 2-3 hour. Don't run any bot in the meantime, go out, have dinner etc. 
Download the latest version 1.2. run the bot. 
I've been running for 3 hours at 180k exp without evolve. Haven't gotten ip ban until now.
I'd love to see you donate to Haxton for making this awesome bot!

**Comment by potheed** [comment]
What a shitty thing to say, take your 'business' and do one.
