### ISSUE TITLE
i realy want to donate, but not now.

### ISSUE THREAD

**Issue by 0x320** [d-haxton/HaxtonBot#127]
The BOT says everytime:

Failed recycling items.
and some more small things.

The Bot workend 2 Days ago. (Very very very good)

but now, nothing worked.

i realy realy want to donate, but i want to donate for things there working.

**Comment by ComputerDavid** [comment]
What a shitty thing to say.  Donations encourage the coders to put more time into the project.  

You say it worked 2 days ago very very very good?  Doesn't THAT deserve at least a dollar?  Try downloading the latest version (1.2) and look around the Issues/comments section here.  A lot of the times it is user error.
