### ISSUE TITLE
pokemon transfered BUT CANDY DIDN'T INCREASE

### ISSUE THREAD

**Issue by Breez3** [d-haxton/HaxtonBot#128]
admin, PLEASE PLEASE fix it.  all the transfered pokemon give no candy.
i stop the bot and open my account on pokenurse to level up manually, i got no candy from the transfered pokemon.
is my config wrong or it's not on the config yet????
thanks.

**Comment by snyy** [comment]
Hmmm, Not sure why you would be having this problem. If you dont already have the latest version get it  and thats all i can say. ;(

**Comment by Breez3** [comment]
i got the latest version/latest release (v 1.2).

do i have to change this default line on the config to "true" ????
but its wroted UNSUPORTED AT THE MOMENT.

is it because this line not worked yet, so the bot "EAT" ALL the candy to evolve RANDOM or lower CP pokemon and i got nothing left to evolve/level up my highest IV/CP pokemon.

****************************************************************************

    
    
****************************************************************************

PLEASE HELP.

**Comment by TurntKFC** [comment]
its because it probably evolved your pokemon or powered it up :/ fix your config

**Comment by Breez3** [comment]
@snyy @TurntKFC @d-haxton @Devlix this is my config, PLEASE point me which one do i've to change to prevent the bot evolve randomly and keep my candy after transfering lowest iv/cp pokemon

###########################################################################
    
    <add key="KeepMinIvPercentage" value="90" />
    <add key="KeepMinCp" value="1900" />
    <add key="WalkingSpeedInKilometerPerHour" value="180" />
    <add key="KeepPokemonsThatCanEvolve" value="false" />
    <add key="TransferDuplicatePokemon" value="true" />
    <add key="UsePokemonToNotCatchFilter" value="false" />
    <add key="KeepMinDuplicatePokemon" value="1" />
    <add key="PrioritizeIvOverCp" value="true" />

    
    
    <add key="Proxy" value ="" />

    <add key="UseLuckyEggs" value="false" />
    <add key="UseBurstMode" value="true" />
    <add key="EvolveAll" value="true" />

    
    
    

    <add key="TeleportInsteadOfWalking" value="true" />

    
    <add key="UseGpxPathing" value="false" />
    <add key="GpxFile" value="gpx.test" />
  </appSettings>
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
      <target name="logfile" xsi:type="File" fileName="file.txt" />
      <target name="console" xsi:type="ColoredConsole" layout="${date:format=yyyy-MM-dd HH\:mm\:ss} ${message}" useDefaultRowHighlightingRules="true" />
    </targets>

    <rules>
      <logger name="*" minlevel="Trace" writeTo="logfile" />
      <logger name="*" minlevel="Info" writeTo="console" />
    </rules>
  </nlog>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="C5" publicKeyToken="282361b99ded7e8e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.5947.17248" newVersion="2.4.5947.17248" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by TurntKFC** [comment]
on the line
<add key="UseLuckyEggs" value="false" />
<add key="UseBurstMode" value="true" />
<add key="EvolveAll" value="true" />  <<<<<<<------ Turn this one too false

**Comment by Breez3** [comment]
@TurntKFC  please edit your comment, it show me no line to edit. it just show : 
" <<<<<<<------ Turn this one too false ".
thanks

**Comment by TurntKFC** [comment]
@Breez3 for some reason it doesn't show code but its the one under burst mode its called evolve all set it too false

**Comment by TurntKFC** [comment]
if it worked please close issue so other people can be helped too thanks

**Comment by bonjohn** [comment]
which line?
