### ISSUE TITLE
Errors In Game And IP Ban Help 

### ISSUE THREAD

**Issue by TurntKFC** [d-haxton/HaxtonBot#130]
Is the bot banning your ip if you have another bot on like necrobot or pokesniper2? Sometimes i keep getting the errors and i wanna keep it overnight with my main ip not vpn but it keeps banning my ip saying checking inventory every single time and i checked other bots like ultimate bot(bot manager) it says possible i got a temp ip ban and an annoying  thing in the program it is saying encounter failed with reason: encounter not in range is their a way to extend range.. any suggestions what i should do... If Dev reads this please add something so i can use pokesniper with it.. Anyway thanks for the program

**Comment by ComputerDavid** [comment]
1. I hear you can have NecroBot on the same IP as Haxton. But no others. (No multiples of Haxton either, even if on separate computers, same IP)

2. Encounter not in range means you are soft banned.  You might try to google "quickspin" and that may help you un-ban your account in a couple of minutes. No guarantees!
