### ISSUE TITLE
Bot can't login to my account at all :(

### ISSUE THREAD

**Issue by TravisMeister** [d-haxton/HaxtonBot#131]
Hi, the bot suddenly stopped login into my google account like a few hours ago, I was using just fine, and my account is not banned aswell, also I'm using VPN which I switch IP's every 30 minutes to avoid bans.

But somehow after I received a message on my email saying that there was suspicious activity on my account, google locked me the fuck out I assume. I looked everywhere on how to fix this, but I can't seem to disable this stupid ass IP protection. Any idea on how should I proceed?

**Comment by TravisMeister** [comment]
Also it can't be that im IP banned cause I tried even with my own ip(which it isn't banned) and I still can't login...

**Comment by TurntKFC** [comment]
try checking your gmail too see what wrong probably someone logged in your account if so try changing your password but don't put 2 step verification cus it doesn't work with bots and try to be a little bit more specific on suspicious activity post the email text here

**Comment by TravisMeister** [comment]
I don't think it was anybody login into my account, since the IP's match my VPNs.
On this page https://security.google.com/settings/security/activity
I see the devices and their IP's, I already allowed the VPN's there but still I get stuck on the login error endlessly. I already tried everything, even using my own IP, it just simply does not connect.

**Comment by snyy** [comment]
2 step verification

**Comment by snyy** [comment]
ALSO if you switch IPs To many times
