### ISSUE TITLE
Evolution to third Pkmn

### ISSUE THREAD

**Issue by Dangery1** [d-haxton/HaxtonBot#134]
I´m running the bot now for about 14 hours and it is purely insane.
The only thing I dont get it is how to evolve Ivysaur, Charmeleon, Wartotle, Kadabra, well u get the point.

The bot just evolves the first Pokemon of the evolution and then sends the weakest evolution away. 
What exactly should I change in the CONFIG File?

I tried by myself but always fucked it up somehow, so any tip is appreciated :)

**Comment by Flaion432** [comment]
go to the UserSettings folder and change the pokemons that you want to evolve in the file called "Pokemons to Evolve"

 You need to add in the First and the Second Evolution to get to third Automatically

**Comment by Dangery1** [comment]
Thx mate,
I just changed it.

**Comment by Dangery1** [comment]
Seems like it only keeps the second evolution longer now.
The moment he has 25 bonbons again, the bot evolves the first evolution again.
![pkmntoevolve](https://cloud.githubusercontent.com/assets/20889399/17583921/ec13519a-5fb3-11e6-834d-a10c77e0bbdb.JPG)

**Comment by MattShawz** [comment]
@Dangery1 Maybe it is a list that is read from top to bottom like an array? So you have to put the second evolution first and it will save candy for that, or I could be completely wrong and it is a case of it evolves whatever it can. If it evolves whatever it can then it may be a case of having to change it each time. Maybe this is a feature that can be added.

**Comment by Dangery1** [comment]
Just in case I tried this now, but does not work as well.
Funny to have an account on level 34 but missing all third evolutions besides Pidgeot lol
dunno y he got evolved and the other didn´t
