### ISSUE TITLE
task crashed or cancelled 

### ISSUE THREAD

**Issue by cameron3911** [d-haxton/HaxtonBot#135]
![capture](https://cloud.githubusercontent.com/assets/20918170/17582737/1929eb2e-5fcf-11e6-930d-7c4b42ed0a92.PNG)
 help please!

**Comment by E4zyE** [comment]
I have the same problem. Settings:

- password is 100% correct
- no unnecessary spaces in config
- Necrobot on the same ip works fine, so no ip ban

    <add key="AccountType" value="Google" />
    
    <add key="GoogleEmail" value="mail@gmail.com" />
    <add key="GooglePassword" value="password" />

Anyone?

**Comment by ComputerDavid** [comment]
I restarted my network (Modem and Router) and it went away for me.
(well, I quit the bot first, then reset, and problem never returned)

**Comment by snyy** [comment]
I know you say this isn't an IP ban but It seems like it is OR you need to disable 2 step verification on your google account but im not sure how to do that sorry,

**Comment by MattShawz** [comment]
I had the same problem last night and after trying a few bots worked out my issue was an IP Ban. I reset my router and then turned it back on and didn't run the bot overnight. In the morning I loaded it back up and changed my start location slightly. example 37.790038, -122.404964 changed to 37.790185, -122.404874. I've now been running for 2 hours without a problem. 

From what others have said I think your best attempt would be to turn off your router and quit the bot, keep the router off for a couple of minutes then turn back on and change the start location. This worked for me and is all I can suggest for you after doing some research. Sadly my experience with this problem ends there :( sorry I can't help anymore

**Comment by snyy** [comment]
If you need any help go to my post. I solved most of these issues! Turning off 2-Step Verification
In “Signing in & security” section of My Account, select 2-Step Verification. Sign in with your username, password, and verification code if asked.
Select Turn off 2-Step Verification.
A pop-up window will appear to confirm that you want to turn off 2-Step Verification. Select Ok.

**Comment by MattShawz** [comment]
If it is 2 step verification then @snyy has put together a nice litte help guide for some errors in #132 . Thanks for putting the info together! 👍

**Comment by snyy** [comment]
thank
