### ISSUE TITLE
Always IP BAN

### ISSUE THREAD

**Issue by agustyn7** [d-haxton/HaxtonBot#138]
i get ban every 1 hour i tried everything i closed teleport false and not location cycle but i get ban.
i am afraid of get ban perminantly :s

**Comment by snyy** [comment]
are you running the new version of the haxton bot. if you are take a look at my post i went over every issue and how to solve it hope it helps.

**Comment by snyy** [comment]
get a vpn or latest version of haxton or look at my in depth guide of IP bans and error fixes

**Comment by spreston84** [comment]
snyy where can I download the newest version. Also where is your guide?

**Comment by Nomaan12345** [comment]
where is the guide? and which VPN  should i use?

**Comment by ipkpeople** [comment]
@Nomaan12345 I used cyberghost http://www.cyberghostvpn.com/

But @snyy why do i keep getting IP banned even after changing IP and using only 1 bot? Also I am using the latest of Haxton Bot 1.2
First few minutes after changing IP it is fine but then I'll have EncounterNotInDistance which is IP banned.

**Comment by snyy** [comment]
click this #132 it will take you to my guide

**Comment by snyy** [comment]
and i would stop botting for a day then try again

**Comment by snyy** [comment]
It could also be @ipkpeople that you are switching ips to much that also flags the system. go though my full guide for the most detailed descriptions #132 <---- click for my guide

**Comment by ipkpeople** [comment]
Thank you for the clarification @snyy

**Comment by snyy** [comment]
youre welcome
