### ISSUE TITLE
Keep "updating Inventory"

### ISSUE THREAD

**Issue by loveintrt** [d-haxton/HaxtonBot#142]
1 bot, reset router before run v1.2, got "updating inventory" after 1+hr running smoothly. What's the issue and how to fix now??

**Comment by TurntKFC** [comment]
get cyberghost vpn and run it but wait awhile before you run haxton and cyberghost wait an hour or 2 then you can start it up so you wont get temp ip banned

**Comment by snyy** [comment]
#141 look at my post lmao why are people not reading this i have every solution

**Comment by loveintrt** [comment]
Thanks @TurntKFC - Can cyberghost provides separate ip that allows me run 1+ bot?

**Comment by loveintrt** [comment]
- 1. Inventory Loop (Updating Inventory) 
 This is a very common one and basically if you're getting the "Updating Inventory" over and over again then it means You are either IP banned OR its a PokemonGo server issue, but most of the time it's because you are IP banned. IP bans are NOT permanent. You can either use a VPN/Proxy or wait or call your ISP to switch your IP. You can check if you're IP banned if you get on your phone and you don't see and pokestops/gyms and if there aren't any nearby pokemon. If you have the newest Haxton you shouldn't be getting this error. IF THOSE DONT WORK TRY TO QUIT BOTTING FOR 1 DAY THEN TRY AGAIN WITH NEWEST VERSION OF HAXTON

I have read your post .. couple times but still not clear and not my case - it was running fine for the first 2 hours and then I got this "updating inventory", from which I am sure it wasn't ban at beginning and in your post - you should not get this error message if you run from newest version.

Any VPN suggestion I could solve this issue?

**Comment by TurntKFC** [comment]
@loveintrt no it cant sadly its a fast xp bot but risky, if your gonna use mutiple accounts use Go Manager, Pokebuddy or Necrobot personally works for me...
