### ISSUE TITLE
Task crashed or cancelled

### ISSUE THREAD

**Issue by MasterManGo** [d-haxton/HaxtonBot#149]
Everything is right in my settings (I'm trying to use a google account) and I can not log in. Why? What should I do?

**Comment by yudanoct** [comment]
same problem for me, i was try to restart my router, pc and other.. but still can't login.. if i try to open another bot, it login success and start to farm.. 

what should i do if i want to use haxtonbot?

**Comment by TurntKFC** [comment]
Try This fix #157
