### ISSUE TITLE
GoogleAuth fail

### ISSUE THREAD

**Issue by Ghenghis** [d-haxton/HaxtonBot#15]
last version seems its broken as it crashes trying to open browser.

works if you have older googleauth tho

**Comment by nthacks** [comment]
I'm having the same issue

**Comment by nthacks** [comment]
It's a server issue, no other bot works either

**Comment by Ghenghis** [comment]
yeah it stopped working even old Auth. here also - Seems like its GoogleAuth is down, maybe to much traffic lol

**Comment by hkinq** [comment]
how can I paste my old google refresh token ?
