### ISSUE TITLE
FIXXXED!! [ TEST IT YOURSELF ] HIGH STABLE XP, STARDUST, KEEPS HIGH CP/IV CONFIG INCLUDED. RECYCLE ISSUE FIX

### ISSUE THREAD

**Issue by qyxii69** [d-haxton/HaxtonBot#151]
FIX! :) ( All credit to the creator of the bot )

upload is here... your welcome.. and a nice config :)

enjoy!

https://mega.nz/#!DIIhDAaT!76wxDbZk9wNoFULEUt9KCFU4feh4KL_7McUNOJA1qRk

Config for perfect settings xp, stardust :) iv recycle :)

----------------------------------------------------------- (copy below)

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>
  <appSettings>
    
    <add key="AccountType" value="Google" />

    
    <add key="DefaultLatitude" value="40.770418086484604" /> 
    <add key="DefaultLongitude" value="-73.97463798522949" />
    <add key="DefaultAltitude" value="11" />

    
    <add key="GoogleEmail" value="google" />
    <add key="GooglePassword" value="google" />
    
    <add key="PtcUsername" value="ptcuser" />
    <add key="PtcPassword" value="ptcpass" />

    
    <add key="KeepMinIvPercentage" value="80" />
    <add key="KeepMinCp" value="1650" />
    <add key="WalkingSpeedInKilometerPerHour" value="180" />
    <add key="KeepPokemonsThatCanEvolve" value="false" />
    <add key="TransferDuplicatePokemon" value="true" />
    <add key="UsePokemonToNotCatchFilter" value="false" />
    <add key="KeepMinDuplicatePokemon" value="0" />
    <add key="PrioritizeIvOverCp" value="true" />

    
    
    <add key="Proxy" value ="" />

    <add key="UseLuckyEggs" value="false" />
    <add key="UseBurstMode" value="true" />
    <add key="EvolveAll" value="true" />

    
    
    

    <add key="TeleportInsteadOfWalking" value="true" />

    
    <add key="UseGpxPathing" value="false" />
    <add key="GpxFile" value="gpx.test" />
  </appSettings>
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
      <target name="logfile" xsi:type="File" fileName="file.txt" />
      <target name="console" xsi:type="ColoredConsole" layout="${date:format=yyyy-MM-dd HH\:mm\:ss} ${message}" useDefaultRowHighlightingRules="true" />
    </targets>

    <rules>
      <logger name="*" minlevel="Trace" writeTo="logfile" />
      <logger name="*" minlevel="Info" writeTo="console" />
    </rules>
  </nlog>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="C5" publicKeyToken="282361b99ded7e8e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.4.5947.17248" newVersion="2.4.5947.17248" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by qyxii69** [comment]
![image](https://cloud.githubusercontent.com/assets/20846464/17607815/75663254-6028-11e6-8c58-269f4109366b.png)

**Comment by TurntKFC** [comment]
whats fixed?

**Comment by UraharaKisuke07** [comment]
How much stable xp are you getting?

**Comment by qyxii69** [comment]
600 to 640 pokemon/ph... and 190k to 240k stable xp :)

**Comment by qyxii69** [comment]
<add key="KeepMinDuplicatePokemon" value="0" /> is key with my config. AND you also get to keep you nice iv's and high cp's :)

**Comment by UraharaKisuke07** [comment]
You have evolve on. And getting 190k to 240k. I have evolve off and getting 170k stable. Guess I'll stick to my config. 
But thanks for sharing! this will help a lot of people.

**Comment by qyxii69** [comment]
![image](https://cloud.githubusercontent.com/assets/20846464/17607996/bfbbfe00-6029-11e6-997d-84237f35a014.png)

**Comment by qyxii69** [comment]
UraharaKisuke07 - that's stable xp. mine goes to 290k roughly 30% of the time :)

**Comment by TurntKFC** [comment]
is the download you included  v1.2?

**Comment by qyxii69** [comment]
It's 1.1 with a fix. so it's much better than 1.2.. even if it's an older version. it's a fixed older version :)

**Comment by TurntKFC** [comment]
so as long as i am running one bot i wont get ip banned?

**Comment by qyxii69** [comment]
nope. AND check for how long i've been running the bot

![image](https://cloud.githubusercontent.com/assets/20846464/17608359/4cdbd07e-602c-11e6-8b7f-59751afc83ee.png)

**Comment by TurntKFC** [comment]
wow longest i ran it was an hour before it started crashing alot thanks gonna try it out right now

**Comment by qyxii69** [comment]
no problem man! :+1:

**Comment by TurntKFC** [comment]
can i also turn on lucky eggs?

**Comment by qyxii69** [comment]
yeah ;) forgot that now. but im running it, just before i go to work :)

**Comment by TurntKFC** [comment]
Cool Thanks A lot man :100:

**Comment by lkaragjo** [comment]
where do you download the config?

**Comment by qyxii69** [comment]
You just copy it :) look at the start :)

**Comment by lkaragjo** [comment]
I downloaded the link with Haxton but where do I download the config. I tried to copy paste after the word below but it just crashed when I opened it.

**Comment by qyxii69** [comment]
Did you fill in these babies?



<add key="GoogleEmail" value="@gmail.com />
<add key="GooglePassword" value="Password" />

<add key="PtcUsername" value="ptcuser" />
<add key="PtcPassword" value="ptcpass" />

you edit CONFIG file within 

" PokemonGo.Haxton.Console.exe "
right click + edit -- >>> cntr + A... and paste the config :)

**Comment by lkaragjo** [comment]
[xml version.pdf](https://github.com/d-haxton/HaxtonBot/files/414434/xml.version.pdf)

I copy pasted the following and put my google account and password

**Comment by lkaragjo** [comment]
any help? maybe someone can upload a full picture of what the config shoud look like. I am def confused somewhere

**Comment by lkaragjo** [comment]
Never mine I forgot I changed the god damn password to my gmail that's why it was not working. I tried PTC and it works.

**Comment by Spayds** [comment]
hello can u change about recycle item?

**Comment by MasterManGo** [comment]
wtf? help me please
![captura](https://cloud.githubusercontent.com/assets/20977622/17611694/34770430-600f-11e6-92dd-a4828f58de96.PNG)

**Comment by TurntKFC** [comment]
your ip banned either close the program and wait 1-2 or more hours or use vpn and make sure no other bots r running when running this program

**Comment by putra1122** [comment]
![fak](https://cloud.githubusercontent.com/assets/20982730/17612090/ef9b9308-6077-11e6-8b43-79ec246e84f1.jpg)

help me.. stuck at recycling that incub T_T

**Comment by MasterManGo** [comment]
Thx for the help, now is working! :dancer: :smile:

**Comment by ahmedyali** [comment]
Hi, why is catch success nearly always 0?

**Comment by ahmedyali** [comment]
Btw thank you very much for your config!

**Comment by MasterManGo** [comment]
Is that normal? Full catch flee :/ 
![captura](https://cloud.githubusercontent.com/assets/20977622/17613082/27bc1d2e-601f-11e6-879d-ca49b4b22522.PNG)

**Comment by TurntKFC** [comment]
#157 Check My Fix For Ip Ban and Fast XP

**Comment by MasterManGo** [comment]
So if I have this problem, I also have to do the same fix?
![captura](https://cloud.githubusercontent.com/assets/20977622/17613310/59465524-6021-11e6-8377-d8b503fd7d90.PNG)

**Comment by kenlim123** [comment]
having the same issue as u @MasterManGo
