### ISSUE TITLE
All Pokemon CatchFlee but Pokestops is Works

### ISSUE THREAD

**Issue by ule1004** [d-haxton/HaxtonBot#154]
since 30min all Pokemon CatchFlee but PokeStops work.

**Comment by ak1ba** [comment]
same

**Comment by Breez3** [comment]
HELP. got the same problem this morning.  dev please fix it.
is it new update form pokemon go dev? to prevent bot from cacthing all pokemon.

**Comment by loveintrt** [comment]
![catchflee](https://cloud.githubusercontent.com/assets/20972397/17610529/e26690f4-600c-11e6-85a2-3a6d9f75c1a0.jpg)

Same issue. what's the reason and solution???

**Comment by Gernatch** [comment]
Same here. What version are you on? 1.1 or 1.2?

**Comment by ule1004** [comment]
I used 1.1 and 1.2 version and there same

**Comment by Gernatch** [comment]
Just to add. I'm on the new 1.1 release.

**Comment by UraharaKisuke07** [comment]
Looks like this is some new kind of softban. Stop playing from your account for a while and it should go away.

**Comment by ak1ba** [comment]
This is only happening to my main account. It's catching pokemon on my other account. I'll wait a couple hours and see if my main starts working again.

**Comment by lbosarge** [comment]
Same thing happens for me with 1.2 but if I use NecroBot it works fine.

**Comment by Gernatch** [comment]
I've tried 1.1, 1.2 and NecroBot. Same issue on all. Is this the end?

**Comment by UraharaKisuke07** [comment]
not the end lol. Just use other bots who have low exp/hr for now and wait for devs to confirm/update the Haxton bot.

**Comment by Gernatch** [comment]
Yeah, using NecroBot for now. While it still has the same problem, I can set it up to only farm Pokestops for now.

**Comment by UraharaKisuke07** [comment]
I'm using necrobot as well but i can catch pokemon. You just have to wait sometime (unknown atm) for the fleeban to lift and then you can start catching pokemons with necrobot. Don't use your account in the meantime though.

**Comment by UraharaKisuke07** [comment]
The wait time for fleeban is 2 hours. confirmed.

**Comment by Gernatch** [comment]
Also need to somehow figure out  the threshold of what causes it.

**Comment by mejuez** [comment]
Same with me, how to fix this problem. Still now i can't catch any pokemon. Always catchflee...
