### ISSUE TITLE
BEST FIX FOR IP BAN + Showthread HAXTON(SYTHARIX EDIT)

### ISSUE THREAD

**Issue by TurntKFC** [d-haxton/HaxtonBot#157]
Hey Guys I Know This Program Is Getting You **Ip Banned** and all but I have found a **_fix_** for it on a forum called **mpgh.net**. So lets get right into it...
-First Open This and Read Through It: **http://www.mpgh.net/forum/showthread.php?t=1153307** 
-Once you have done that you must have an account or register and activate account: **www.mpgh.net/forum/register.php**
-Then Lastly Once You Have ^Finished^ that step you can finally download it: **www.mpgh.net/forum/register.php**
If This Works **Please** Give It A **Thumbs Up** :+1: So Other can see the fix... Thanks Credit to:  **Silver Surfer** for posting this thread..
_Updates On How Long Its Been Working_
Please Help The Developers By Either Donating or Following Their Social Media
Social Media
https://twitter.com/sytharix
http://www.mpgh.net/forum/member.php?u=312687
Donations For Dev n Editor
https://discord.gg/Xt5JnHS (Developer/Creator)
https://discord.gg/QcbU7Ms (Sytharix)
**

If You have any questions just reply below

** :100: 
Test In Sytharix Edit for Haxton:
-Been Working An Hour No Problem
-Getting 340k Xp An Hour With Egg and 150k/160k Without

**Comment by TurntKFC** [comment]
Posting Screenshot soon...

**Comment by TurntKFC** [comment]
![fixit](https://cloud.githubusercontent.com/assets/20001179/17613097/72f18358-600e-11e6-936d-70ef859bd2f0.PNG)

**Comment by d-haxton** [comment]
get the fuck out of here you faggots
