### ISSUE TITLE
Stuck at inventory updating

### ISSUE THREAD

**Issue by Nordsted** [d-haxton/HaxtonBot#18]
![stuck at inventory](https://cloud.githubusercontent.com/assets/10519127/17216406/cfa25ebc-54e0-11e6-8162-7e42417c976c.png)

**Comment by zhu8808** [comment]
try again now, it would be your network issue.

**Comment by Nordsted** [comment]
Okay it got a bit further now before crashing. Still doesn't seem right that it has to reconnect to Ptc all the time... Or is this the teleporting part of the bot?

![Uploading stuck at inventory.png…]()

**Comment by Nordsted** [comment]
![stuck at inventory](https://cloud.githubusercontent.com/assets/10519127/17217240/ee903210-54e3-11e6-836b-1e71f12b7e76.png)

**Comment by Nordsted** [comment]
works for me now.
