### ISSUE TITLE
"Fatal Error"

### ISSUE THREAD

**Issue by SpeedyPvP7** [d-haxton/HaxtonBot#20]
When I launch haxton I get this error: https://gyazo.com/9e64ff93c44c4802eae901ab370ac3db. I tried the compiled and uncompiled version. Please help

**Comment by Thunderkill** [comment]
I get the exact error

**Comment by Ghenghis** [comment]
same here - Google Token problem I think - old version working but crashes within 20-30 mins every time

**Comment by Thunderkill** [comment]
It seems that you need to use commas instead of periods when setting coordinates.

73.123 is wrong, you need to do 73,123
