### ISSUE TITLE
pokestop farm only?

### ISSUE THREAD

**Issue by Epenite** [d-haxton/HaxtonBot#28]
Hello, I would like to know if it was possible for me to farm pokestop and avoid capturing pokemons? How can I do that please?

**Comment by H3RB4LS** [comment]
It's probably not the most efficient way, but under the UserSettings, add all Pokemon in PokemonToAvoid.cfg (don't forget to set  <add key="UsePokemonToNotCatchFilter" value="true" /> under config) and it wouldn't pick up any. Might take time skipping them; would be better to edit the code to suit your needs but if you don't want to do that...

**Comment by Epenite** [comment]
I'll do that and try a few minutes see how it goes. Thanks for helping!

**Comment by Epenite** [comment]
Does not work, after blacklisting all pokemons I can't log in : Fatal error when trying to connect.

**Comment by AncientGen** [comment]
the fatal error luckily had nothing to do with your blacklisted pokémons.
All bots are/were down at the moment, google changed their api-login methods.

**Comment by H3RB4LS** [comment]
Upon my searches, I believe I came across exactly what you're looking for: http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/565188-pokesnipe-ccrts-pokemon-sniping-bot.html#post3484055  Can't confirm if it works with latest update, so might have to wait but yea
