### ISSUE TITLE
1 sec help

### ISSUE THREAD

**Issue by AncientGen** [d-haxton/HaxtonBot#3]
installed everything but i came from a noobfriendly bot
changed the config.
Where do I enter my login credentials, my API key and how do i launch it?
thanks in advance!

**Comment by timelf123** [comment]
> Open up app.config within your PokemonGo.Haxton.Console folder/project

no api key needed, just coords

**Comment by AncientGen** [comment]
oke but then how do i launch it.. and connect it to my gmail/PTC account?
Thanks for the effort btw man

**Comment by timelf123** [comment]
Look at `App.config` for where to put your auth info, then build it 
![step1](http://i.imgur.com/S2baK3v.png)
![step2](http://i.imgur.com/U4FSp44.png)

Then it will be in bin/Release

**Comment by AncientGen** [comment]
ah crap overlooked the fact that it might need to be build.
all other bots i had were cmd-standalones. any tips if visual studio expired?
some free stuff?

**Comment by timelf123** [comment]
visual studio community is free

**Comment by AncientGen** [comment]
thanks alot for the info and efforts man!! you rock.

**Comment by apyapy** [comment]
hey sorry for my lack of knowledge, well i am exploring App.config and cannot identify where to insert Auth info. help?

**Comment by d-haxton** [comment]
No auth info, just run the bot and it'll follow unless you're trying to use Ptc.

**Comment by scorpionking674** [comment]
when i opened it, it asked to switch .netframework from 4.6.2 to 4.6.1, i tried to download it but it wont let me, cuz its already updated version. im getting 73 errors while building

**Comment by chopraaa** [comment]
Then remove the version you don't need.
