### ISSUE TITLE
Commits 40 Burst Mode issue

### ISSUE THREAD

**Issue by TehChozinOne** [d-haxton/HaxtonBot#35]
Google Login
Walking Mode
Burst Mode On
180km/h
Evolve On(Zubat, Rattata, Pidgey)
Evolve All Off
Lucky Egg Off
Central Park, NY
Not Soft Ban
So many Catch Error and Catch Flee
Bot also fail to transfer and evolve(repeat transferring message same pokemon over and over)
Bot also refuse to visit any Pokestops

===================================

Google Login
Teleport Mode
Burst Mode Off
Lucky Egg Off
Central Park, NY
Not Soft Ban
Evolve On(Zubat, Rattata, Pidgey)
Evolve All Off
Bot is working fine
110 ~ 120k exp/h no egg

**Comment by AncientGen** [comment]
I am not sure if they're onto this problem already.
Alot of other stuff is getting fixed but those who have these issues
have had them for quite some time now.
