### ISSUE TITLE
CatchError

### ISSUE THREAD

**Issue by ants333** [d-haxton/HaxtonBot#37]
why CatchError ?
Probably more than 90%.. CatchError

How do fix it?

**Comment by geomchi7** [comment]
cf catcherror ~30% with me

**Comment by d-haxton** [comment]
I'm aware. I don't know whats really going on here. Need to look into it more.

**Comment by pokedes** [comment]
would it be caused by the google map update recently?

**Comment by d-haxton** [comment]
Fixed.
