### ISSUE TITLE
inaccurate EXP/hr PK/h

### ISSUE THREAD

**Issue by aapikz** [d-haxton/HaxtonBot#47]
i just notice when i logged my account for 30min my exp skyrocketing around 600k/exp and 800-900 pokemon/hr.. because statistics updates every 30sec or 1min? 
would it be possible to make update it every seconds or actions? just like ferox, necro, and pokecolor bot? i just really want to see my accurate exp/h ... thx more power

**Comment by d-haxton** [comment]
exp per hour is accurate
