### ISSUE TITLE
Still get Fatal Error

### ISSUE THREAD

**Issue by benawesome100** [d-haxton/HaxtonBot#51]
2016-07-30 10:43:58 Fatal error, attempting to restart
2016-07-30 10:43:58 Logging in with account type: Google

I still get this and I am sure all Logins are correct and I have done everything correctly.

**Comment by Hoxsus** [comment]
Go to Control Panel -> Clock, Language, and Region -> Region -> Additional settings... -> Currency tab -> Change decimal symbol to a dot (".") and apply changes on both menus.

**Comment by Defeat3d** [comment]
Go to Control Panel -> Clock, Language, and Region -> Region -> Additional settings... -> Currency tab -> Change decimal symbol to a dot (".") and apply changes on both menus.

**Comment by benawesome100** [comment]
My setting are correct. 
![image](https://cloud.githubusercontent.com/assets/20733379/17267672/583e0128-5652-11e6-95cf-5c2dc3d89c36.png)
![image](https://cloud.githubusercontent.com/assets/20733379/17267678/66ce530a-5652-11e6-9f31-772cab2ab739.png)
