### ISSUE TITLE
Fatal Error Fatal Error

### ISSUE THREAD

**Issue by Navyguy330** [d-haxton/HaxtonBot#55]
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error
Fatal Error

Very annoying, please fix

**Comment by Ry6er** [comment]
From Nulled.io
" FATAL ERROR SOLUTION
1. Go to "Settings" in Windows 10
2. Click "Time and Language"
3. Click "Region and Language"
4. Click "Additional date, time, & regional settings"
5. Click "Region: Change date, time, or number formats"
6. Click "Additional settings..."
7. Change "Decimal Symbol" from comma (,) to period (.) "

**Comment by Navyguy330** [comment]
I'm in the US. I already use .

**Comment by Ry6er** [comment]
Try this sytharix version it worked for me
also ptc dosent seem to work at all 
https://cdn.discordapp.com/attachments/208694564930715651/208755852771983361/Haxton-Sytharix_Edit_v2.2.zip

**Comment by Gretagas** [comment]
are you getting a fatal error with the google log in or ptc?

**Comment by Navyguy330** [comment]
Actually PTC

**Comment by Gretagas** [comment]
shoot thought it was google just fixed mine problem, my ptc login are running fine wish I knew how to help with that.  You sure all the log in info is correct you tried another account yet?
