### ISSUE TITLE
Out of Pokeballs - Inventory Updating Issue

### ISSUE THREAD

**Issue by Ghenghis** [d-haxton/HaxtonBot#6]
Never have any pokeballs. all the time at high levels, need to have bot farm 5x more pokestops then attack pokemon - recycle option for account that have 1000 storage please vs the 300

maybe after mid lv20's everyone will need more pokeballs lv30 for sure, also stuck at inventory for long time, update buffer for stats is to slow should be realtime update for stats.

maybe next to add pokestop farms for the bot

Great bot, one of the best!!!!! Thank you for sharing!!!

**Comment by dhaxton** [comment]
You need to be in a spot with lots of pokestops
