### ISSUE TITLE
Starting bot , updating inventory, starting bot 

### ISSUE THREAD

**Issue by cr1smc** [d-haxton/HaxtonBot#65]
> 2016-07-30 21:50:47 Starting bot.
> 2016-07-30 21:50:47 Logging in with account type: Google
> 2016-07-30 21:50:48 Updating inventory at 30.07.2016 21:50:48
> 2016-07-30 21:50:49 Recycling item(s): ItemUltraBall x1
> 2016-07-30 21:50:50 Recycling item(s): ItemMaxPotion x25
> 2016-07-30 21:50:51 Updating inventory at 30.07.2016 21:50:51
> 2016-07-30 21:50:52 Updating inventory at 30.07.2016 21:50:52
> 2016-07-30 21:50:53 Starting bot.
> 2016-07-30 21:50:53 Logging in with account type: Google
> 2016-07-30 21:50:54 Updating inventory at 30.07.2016 21:50:54
> 2016-07-30 21:51:00 Starting bot.
> 2016-07-30 21:51:00 Logging in with account type: Google
> 2016-07-30 21:51:01 Updating inventory at 30.07.2016 21:51:01
> 2016-07-30 21:51:02 Updating inventory at 30.07.2016 21:51:02
> 2016-07-30 21:51:04 Updating inventory at 30.07.2016 21:51:04
> 2016-07-30 21:51:06 Recycling item(s): ItemUltraBall x1
> 2016-07-30 21:51:07 Starting bot.
> 2016-07-30 21:51:07 Logging in with account type: Google
> 2016-07-30 21:51:08 Updating inventory at 30.07.2016 21:51:08
> 2016-07-30 21:51:08 Updating inventory at 30.07.2016 21:51:08
> 2016-07-30 21:51:11 Updating inventory at 30.07.2016 21:51:11
> 2016-07-30 21:51:12 Updating inventory at 30.07.2016 21:51:12
> 2016-07-30 21:51:13 Updating inventory at 30.07.2016 21:51:13
> 2016-07-30 21:51:15 Starting bot.
> 2016-07-30 21:51:15 Logging in with account type: Google

IS this normal?

**Comment by jakesmurf** [comment]
This usually means that servers are struggling and it can't establish a good connection, ala it's timing out when trying to update inventory.  It usually resolves itself eventually when the servers start working again.

**Comment by bdejean** [comment]
Maybe the timeout is to short ?

> 2016-07-31 07:24:31.4795|INFO|PokemonGo.Haxton.Bot.Login.PoGoLogin|Logging in with account type: Google
> 2016-07-31 07:24:32.7736|INFO|PokemonGo.Haxton.Bot.Bot.PoGoBot|Starting bot.
> 2016-07-31 07:24:34.2657|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:24:34
> 2016-07-31 07:25:06.6195|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:25:06
> 2016-07-31 07:25:39.8954|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:25:39
> 2016-07-31 07:26:13.4653|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:26:13
> 2016-07-31 07:26:45.8222|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:26:45
> 2016-07-31 07:27:19.1121|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:27:19
> 2016-07-31 07:27:52.3090|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:27:52
> 2016-07-31 07:28:24.6158|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:28:24
> 2016-07-31 07:28:57.8607|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:28:57
> 2016-07-31 07:29:31.1197|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:29:31
> 2016-07-31 07:30:05.1596|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:30:05
> 2016-07-31 07:30:37.6545|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:30:37
> 2016-07-31 07:31:11.5694|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:31:11
> 2016-07-31 07:31:45.5763|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:31:45
> 2016-07-31 07:32:17.9312|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:32:17
> 2016-07-31 07:32:51.0041|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:32:51
> 2016-07-31 07:33:24.6700|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:33:24
> 2016-07-31 07:33:57.1169|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:33:57
> 2016-07-31 07:34:29.5797|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:34:29
> 2016-07-31 07:35:02.2626|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:35:02
> 2016-07-31 07:35:34.6634|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:35:34
> 2016-07-31 07:36:07.0813|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:36:07
> 2016-07-31 07:36:40.3422|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:36:40
> 2016-07-31 07:37:13.5067|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:37:13
> 2016-07-31 07:37:47.0317|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:37:47
> 2016-07-31 07:38:20.2596|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:38:20
> 2016-07-31 07:38:54.6256|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:38:54
> 2016-07-31 07:39:28.3685|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:39:28
> 2016-07-31 07:40:02.3164|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:40:02
> 2016-07-31 07:40:35.1063|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:40:35
> 2016-07-31 07:41:08.3822|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:41:08
> 2016-07-31 07:41:41.4391|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:41:41
> 2016-07-31 07:42:15.4780|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:42:15
> 2016-07-31 07:42:47.9259|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:42:47
> 2016-07-31 07:43:20.5308|INFO|PokemonGo.Haxton.Bot.Inventory.PoGoInventory|Updating inventory at 31/07/2016 07:43:20
