### ISSUE TITLE
how to snipe? what is location.cfg? how to enabled it? no instructions? guides?

### ISSUE THREAD

**Issue by aapikz** [d-haxton/HaxtonBot#69]
i start the bot from scratch  and the bot is really lack of guides, wiki page has no guide or info.. i hope you put an instruction..
theres dozens of people spamming in discord chat and no ones volonteer for help

**Comment by mizax** [comment]
just paste coordinates into console and press enter

**Comment by sagiGL** [comment]
doesn't snipe . its just say its sniping but doesn't catch any of the target u try to snipe

**Comment by bjamikel** [comment]
@sagiGL 
![snipe](https://cloud.githubusercontent.com/assets/20750840/17277322/78477d8e-5740-11e6-8904-4e892df93b60.png)

**Comment by lgndz** [comment]
enable quick edit and paste coord into the bot while its running

**Comment by sagiGL** [comment]
weird for me it doesn't snipe. the coords are good since they got verified in discord. <img width="751" alt="screen shot 2016-07-31 at 7 33 20 pm" src="https://cloud.githubusercontent.com/assets/16352229/17277826/afd9b9a0-5755-11e6-937a-825141fa7866.png">
