### ISSUE TITLE
latest rev is brokes everything... bot don't do anything. just spaming inventory

### ISSUE THREAD

**Issue by aapikz** [d-haxton/HaxtonBot#7]
im pretty sure my coordinates has 180+ pokestops in central park. but it doesnt moves around, picks pokestop, or capture pokemon. it just spam my inventory like no tomorrow

**Comment by apyapy** [comment]
@d-haxton same issue here

**Comment by lgndz** [comment]
@d-haxton Same issue here - seems to happen after a short amount of time

**Comment by RaidForums** [comment]
- > http://i.imgur.com/JAmScV7.png

**Comment by dhaxton** [comment]
Verify that you don't have periods in your location if you're from somewhere that requires them.

Or vice versa.

**Comment by lgndz** [comment]
I don't follow... Should we NOT have the period in the Lat/long as per standard?

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Wed, Jul 27, 2016 at 10:49 PM -0400, "dhaxton" <notifications@github.com> wrote:












Verify that you don't have periods in your location if you're from somewhere that requires them.



Or vice versa.

**Comment by d-haxton** [comment]
Try it both ways. See if one works. Use that way.
