### ISSUE TITLE
Task crashed or cancelled

### ISSUE THREAD

**Issue by skillize** [d-haxton/HaxtonBot#77]
i get this error after login on google and then retrying in 5 seconds.. how to fix? on my pc works but on the vps not

**Comment by mizax** [comment]
are you using latest build? are you sure your login credentials are correct?

**Comment by skillize** [comment]
Yes latest build, i create debug and it works on my pc, sure credentials are correct lol im not that dumb

**Comment by mizax** [comment]
basically it means that login failed, sometimes google requires you to enter captcha if you login with same account from different locations

**Comment by skillize** [comment]
i try with new account but it doesnt work as well

**Comment by hoadn** [comment]
Even PTC, it's same to me

**Comment by GwnBott** [comment]
Made new PTC account, error logging in.

**Comment by SudoToEat** [comment]
Same problem

**Comment by lenerdz** [comment]
Same thing here... :(

**Comment by neves768** [comment]
Same \o/

**Comment by LightNeZz** [comment]
Same problem.
