### ISSUE TITLE
new pokemon go api

### ISSUE THREAD

**Issue by levidread99** [d-haxton/HaxtonBot#84]
the bot is not working since the update. would love an update

**Comment by adithyatama** [comment]
yaaa, bot isnt working again, i dont know why,always 0 pokestop everywhere

**Comment by Cleancoke** [comment]
If a fix came this is the bot worth getting over any other, mad props to the creator.

**Comment by AncientGen** [comment]
everytime the game updates, codewrites need to get to work again. give it a day or 2

**Comment by ShallowHacker** [comment]
Lmfao does Haxton even snipe? If not, I pull 300kxp/hr on Necro with Sniping just fine.
I wasn't to fond of Haxton because it didn't have sniping.

**Comment by ShallowHacker** [comment]
But It is very good and stable for pokestops and catching quickly

**Comment by deadbambi** [comment]
@ShallowHacker can you tell me more about this Necro?

**Comment by ShallowHacker** [comment]
Necrobot? Look it up on here on Hithub.

**Comment by deadbambi** [comment]
yeah I found it, I feel like such an idiot lol
thanks though

it looks like it needs updating too, says it cant find pokestops like the rest of them, or is yours working?

**Comment by ShallowHacker** [comment]
No, none of them are working. Sorry If I misled you to think it was working
over the rest. A fix is in the works.

**Comment by deadbambi** [comment]
yeah I figured it wont take long for them to fix it
thanks for the fast replies though :)

**Comment by ShallowHacker** [comment]
No problem, brother. Hard to find understanding people on here. Haha

**Comment by levidread99** [comment]
i made this post just to notify the creator that they updated the API. and because of that the bot needs an update aswell. Most bots should be up and working soon enough, but this was my favorite one so i wanted to notify the creator with this post :)

**Comment by H3RB4LS** [comment]
For anyone interested in the status of the API, check here:
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d65hrv5
