### ISSUE TITLE
Failed To Login

### ISSUE THREAD

**Issue by Majesty01** [d-haxton/HaxtonBot#88]
Failed to login using ptc? maybe even google?
http://image.prntscr.com/image/1e48801b00644dbe92ad220373ad256f.png

**Comment by Nodws** [comment]
Confirm Failed to login on Google

**Comment by Cameron000** [comment]
Same issue, any fix?

**Comment by jordyvandomselaar** [comment]
Bump

**Comment by marcodiniz** [comment]
Same error here - PTC login

**Comment by Nodws** [comment]
Fixed it by instaling necrobot :P 
https://github.com/NECROBOTIO/NecroBot

**Comment by jordyvandomselaar** [comment]
I'm already using Necrobot, it works fine but I want the quick exp for haxton.
