### ISSUE TITLE
Bot hanging?

### ISSUE THREAD

**Issue by Leetferret** [d-haxton/HaxtonBot#90]
![hamg](https://cloud.githubusercontent.com/assets/20695712/17466216/855a28da-5cbf-11e6-84ef-01fb053b49b0.png)
![sss](https://cloud.githubusercontent.com/assets/20695712/17466220/9236a6b4-5cbf-11e6-80fc-81f9135d7c84.png)

**Comment by Kru4444** [comment]
I feel the same as you :(

**Comment by Cameron000** [comment]
go to items under config and change basic egg inc to 100
