### ISSUE TITLE
 <add key="UseLuckyEggs" value="true" />

### ISSUE THREAD

**Issue by chen701** [d-haxton/HaxtonBot#91]
<add key="UseLuckyEggs" value="true" />  
this one not working ?

**Comment by MrJoiny** [comment]
Check if you have any Lucky Eggs.
The Bot isn´t collecting Level Rewards.

**Comment by chen701** [comment]
i have 9 eggs

**Comment by chen701** [comment]
pls help, bot not use lucky eggs when i have eggs with true setting
