### ISSUE TITLE
"Update inventory" in loop after 5-20 minutes of bot working

### ISSUE THREAD

**Issue by xolilomiw** [d-haxton/HaxtonBot#92]
![foto_no_exif](https://cloud.githubusercontent.com/assets/20903544/17477396/bed46428-5d6d-11e6-9d87-fe78956fcea1.jpg)

i have "Update inventory" in loop after 5-20 minutes of bot working
other players has it too, i saw it in discord.

http://img.ctrlv.in/img/16/08/08/57a861787f822.png

**Comment by xolilomiw** [comment]
Ну что за пиздец?

**Comment by Max604** [comment]
Although this isn't an 'official fix' I fix this by either restarting the bot, my internet connection or my computer.
Hope I helped. :)

**Comment by xolilomiw** [comment]
yes, this is not fix.
it is not my computer, it is a virtual server windows 2012 in major hosting company.
no need to check an internet connection or restart system.

**Comment by Max604** [comment]
Not really sure, but that is what fixed it for me.

**Comment by OverCraftX** [comment]
I made a batch file to close and open it each 30 minutes.

@echo off
:loop
start PokemonGo.Haxton.Console.exe
timeout /t 1800 >null
taskkill /f /im PokemonGo.Haxton.Console.exe >nul
goto loop

**Comment by chen701** [comment]
same to me

**Comment by Devilbilly** [comment]
I think the cause is that there's no stop available nearby, thus the bot awaits for half min for next available stop.

**Comment by vehrbox** [comment]
Try changing the ip address or reset the router. It works for me.
