### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by plowzey** [d-haxton/HaxtonBot#95]
http://prntscr.com/c3cugm

Anyhelp?

**Comment by plowzey** [comment]
http://prntscr.com/c3cugm Current config

**Comment by plowzey** [comment]
Current config http://prntscr.com/c3cv7b

**Comment by sandor111** [comment]
Your have too add the default coordinates

**Comment by sandor111** [comment]
Example:
<add key="DefaultLatitude" value="45.460623" />
    <add key="DefaultLongitude" value="9.192992" />

**Comment by sandor111** [comment]
<add key="DefaultLatitude" value="45.460623" />
    <add key="DefaultLongitude" value="9.192992" />

**Comment by VyperYT** [comment]
Stil doesnt work
